"use client";

import { useState } from "react";

export default function Home() {
  const [job, setJob] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [result, setResult] = useState("");

  async function generate() {
    setError("");
    setResult("");
    if (!job.trim()) {
      setError("Please type your dream job first.");
      return;
    }
    setLoading(true);
    try {
      const res = await fetch("/api/roadmap", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ job }),
      });
      const data = await res.json();
      if (!res.ok) {
        setError(data.error || "Something went wrong.");
      } else {
        setResult(JSON.stringify(data, null, 2));
      }
    } catch {
      setError("Network problem. Please check your connection and retry.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <main className="mx-auto max-w-3xl p-6">
      <h1 className="text-3xl font-bold">Career Roadmapper</h1>
      <p className="mt-2 text-gray-600">
        Type a very specific dream job. The roadmap is generated by AI.
      </p>

      <label htmlFor="job" className="mt-6 block font-medium">
        Your dream job
      </label>
      <input
        id="job"
        value={job}
        onChange={(e) => setJob(e.target.value)}
        placeholder="e.g. Full Stack Developer at a climate tech startup"
        className="mt-2 w-full rounded border border-gray-400 p-3 text-black"
      />

      <button
        onClick={generate}
        disabled={loading}
        className="mt-4 rounded bg-blue-700 px-5 py-3 font-semibold text-white disabled:opacity-60"
      >
        {loading ? "Generating..." : "Generate Roadmap"}
      </button>

      {error && (
        <p role="alert" className="mt-4 text-red-600">
          {error}
        </p>
      )}

      {result && (
        <pre className="mt-6 max-h-[60vh] overflow-auto rounded bg-gray-900 p-4 text-sm text-green-300">
          {result}
        </pre>
      )}
    </main>
  );
}